groups:
    - developer
    - bash
    - productivity
    - media
    - hackintosh
    - osx
recipes:
    mac_os_x:
        - applications::rsync
attributes:
    osxdefaults:
        computername: Roma
    homebrewalt:
        apps:
            - trash
            - hr
            - mackup
        cask_apps:
            - airfile
            - dropbox
            - google-drive
            - insync
            - clamxav
            - cleanmymac
            - deeper
            - geekbench
            - omnidisksweeper
            - onyx
            - openemu-experimental
            - skype
            - owncloud
            - pokertracker
            - backuploupe
            - duplicate-annihilator
            - moneywell
            - rescuetime
            - slack
            - slice
            - superduper
