groups:
    - developer
    - bash
    - productivity
    - media
    - hackintosh
    - osx
recipes:
    mac_os_x:
        - applications::rsync
attributes:
    bash_it:
        enabled_plugins:
            aliases:
                - general
                - git
                - gitsvn
                - homebrew
                - laravel
                - osx
                - vagrant
            completion:
                - bash-it
                - brew
                - defaults
                - git
                - git_flow
                - ssh
            plugins:
                - base
                - browser
                - dirs
                - git
                - javascript
                - node
                - nvm
                - osx
                - ssh
                - vagrant
        theme: envy
        dir: /Users/jdigioia/.bash_it
        repository: https://github.com/revans/bash-it.git
    osxdefaults:
        computername: Roma
    homebrewalt:
        apps:
            - trash
            - hr
            - mackup
        cask_apps:
            - airfile
            - dropbox
            - google-drive
            - insync
            - clamxav
            - cleanmymac
            - deeper
            - geekbench
            - omnidisksweeper
            - onyx
            - skype
            - owncloud
            - pokertracker
            - backuploupe
            - duplicate-annihilator
            - moneywell
            - slice
            - superduper
