groups:
    - developer
recipes:
    mac_os_x:
        - osxdefaults::set_computer_name
        - applications::rsync
attributes:
    gems:
        - otask
        - jekyll
    dotfiles:
        bash_it:
            enabled_plugins:
                aliases:
                completion:
                plugins:
            theme:
            dir: ~/.bash_it
            repository: https://github.com/revans/bash-it.git
    osxdefaults:
        computername: Roma
    homebrewalt:
        apps:
            - trash
            - hr
            - mackup
        cask_apps:
            - dropbox
            - google-drive
            - insync
            - clamxav
            - cleanmymac
            - deeper
            - geekbench
            - omnidisksweeper
            - onyx
            - skype
            - pokertracker
            - backuploupe
            - duplicate-annihilator
            - moneywell
            - slice
            - superduper