recipes:
    mac_os_x:
        - nodejs::default
        - applications::php55
        - applications::mysql
        - applications::gems
attributes:
    mysql_root_password: "password"
    homebrewalt:
        apps:
            - python
            - ruby
            - git
            - git-flow
            - android-platform-tools
            - ansible
            - wget
        cask_apps:
            - virtualbox
            - coda
            - codekit
            - transmit
            - tower
            - vagrant
            - diffmerge
            - sublime-text3
    nodejs:
        apps:
            - bower
            - gulp
            - grunt-cli
            - jshint
    gems:
        - capistrano
        - capistrano-composer
        - sass
        - bundler
    php-apps:
        - composer
        - phpunit
