recipes:
    mac_os_x:
        - nodejs::default
        - applications::php56
        - applications::mysql
        - applications::gcc42
attributes:
    mysql_root_password: "password"
    homebrewalt:
        taps:
            - gapple/services
        apps:
            - python
            - ruby
            - git
            - git-flow
            - android-platform-tools
            - ansible
            - wget
            - gnu-tar
            - karn
            - wp-cli
            - whois
            - heroku-toolbelt
            - redis
            - postgresql
            - envoy
            - docker-machine
            - docker
            - curl
            - hub
        cask_apps:
            - atom
            - virtualbox
            - coda
            - firefoxdeveloperedition
            - transmit
            - tower
            - vagrant
            - diffmerge
            - pgadmin3
            - phpstorm-bundled-jdk
            - sequel-pro
            - sublime-text3
            - shuttle
            - webstorm-bundled-jdk
        cask_fonts:
            - source-code-pro
    nodejs:
        apps:
            - bower
            - gulp
            - grunt-cli
            - jshint
    php-apps:
        - composer
        - phpunit
        - php-code-sniffer
        - php-cs-fixer
        - phpdocumentor
