recipes:
    mac_os_x:
        - nodejs::default
        - applications::php56
        - applications::mysql
        - applications::gcc42
attributes:
    mysql_root_password: "password"
    homebrewalt:
        apps:
            - python
            - ruby
            - git
            - git-flow
            - android-platform-tools
            - ansible
            - wget
        cask_apps:
            - virtualbox
            - coda
            - codekit
            - transmit
            - tower
            - vagrant
            - diffmerge
            - sequel-pro
            - sublime-text3
    nodejs:
        apps:
            - bower
            - gulp
            - grunt-cli
            - jshint
    php-apps:
        - composer
        - phpunit
        - php-code-sniffer
