recipes:
    mac_os_x:
attributes:
    homebrewalt:
        apps:
        cask_apps:
            - a-better-finder-attributes
            - a-better-finder-rename
            - alfred
            - bartender
            - big-mean-folder-machine
            - cheatsheet
            - cinch
            - clipmenu
            - dash
            - dropzone
            - hazel
            - mindnode-pro
            - libreoffice
            - omnifocus
            - postbox
            - zipeg
            - flux
            - evernote
            - skitch
            - spectacle
            - vitamin-r
